sudo: required
services:
  - docker

before_install:
  - docker build -t kalle1337/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kalle1337/docker-react npm test

# http://dockerreact2-env.eba-uapcqvad.us-east-2.elasticbeanstalk.com/
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-2"
  env: "DockerReact2-env"
  bucket_name: "elasticbeanstalk-us-east-2-977744108731"
  bucket_path: "docker-react-2"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
